### ISSUE TITLE
What is you experience with object caching & wp-Typography performance?

### ISSUE THREAD

**Issue by mundschenk-at** [allan23/wp-typography#1]
I've recently started to update wp-Typography in https://github.com/mundschenk-at/wp-typography. I've just stumbled upon your fork of the original plugin. Do you have any hard data on the performance with and without object caching?

**Comment by allan23** [comment]
From my own tests on a site I was working on, I determined that there was a 33% performance boost using object caching. Results may vary depending on the site and how many items are getting filtered.

**Comment by mundschenk-at** [comment]
Ah, I nearly forgot. Thanks for the quick reply. I've since implemented some extensive caching of object states via the Transients API, but the new version has not been released yet. Some "in vitro" testing showed a significant reduction in the object initialization overhead when the PHP_Typography can be restored from the transient.
